version: '3'
services:
  rundeck:
    image: rundeck/rundeck:3.3.10
    container_name: rundeck
    restart: always
    labels:
      - "traefik.http.routers.rundeck.entrypoints=websecure"
      - "traefik.http.routers.rundeck.rule=Host(`rundeck.${APPDOMAIN:-local}`)"
      - "traefik.http.services.rundeck.loadbalancer.server.port=4440"
    volumes:
      - rundeck-storage:/home/rundeck/server/data
    networks:
      - traefik-network

volumes:
  rundeck-storage:
  
networks:
    traefik-network:
      external: true
