version: '3'
services:
  plex:
    image: plexinc/pms-docker
    container_name: plex
    restart: unless-stopped
    privileged: true
    environment:
      - TZ=Europe/Helsinki
      - PLEX_CLAIM=${PLEX_CLAIM}
      - ADVERTISE_IP=https://plex.${APPDOMAIN:-local}
    labels:
      - "traefik.http.routers.plex.entrypoints=websecure"
      - "traefik.http.routers.plex.rule=Host(`plex.${APPDOMAIN:-local}`)"
      - "traefik.http.services.plex.loadbalancer.server.port=32400"
    volumes:
      - plex-storage:/config
      - /mnt/media/:/media/
    networks:
      - traefik-network

volumes:
  plex-storage:

networks:
  traefik-network:
    external: true
