version: '3'
services:
  geoserver:
    image: meteofi/geoserver:2.20
    container_name: geoserver
    restart: unless-stopped
    environment:
      - GEOSERVER_CSRF_WHITELIST=geoserver.${APPDOMAIN:-local}
      - GEOSERVER_WMS_TITLE="GeoServer"
    labels:
      - "traefik.http.routers.geoserver.entrypoints=websecure"
      - "traefik.http.routers.geoserver.rule=Host(`geoserver.${APPDOMAIN:-local}`)"
      - "traefik.http.services.geoserver.loadbalancer.server.port=8080"
    volumes:
      - geoserver-storage:/data/geoserver
    networks:
      - traefik-network

volumes:
  geoserver-storage:

networks:
    traefik-network:
      external: true
