version: '3'

services:
  geoserver:
    image: meteofi/geoserver:2.18
    container_name: geoserver
    restart: always
    labels:
      - "traefik.http.routers.geoserver.rule=Host(`geoserver.${APPDOMAIN:-local}`)"
      - "traefik.http.services.geoserver.loadbalancer.server.port=8080"
    networks:
      - traefik-network

networks:
    traefik-network:
      external: true
