version: '3'
services:
  homeassistant:
    container_name: homeassistant
    image: homeassistant/home-assistant:stable
    restart: unless-stopped
    network_mode: host
    volumes:
      - homeassistant-storage:/config
    networks:
      - traefik-local
    environment:
      - TZ=Europe/Helsinki
      
volumes:
  homeassistant-storage:

networks:
    traefik-local:
      external: true

