version: '3'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    restart: unless-stopped
    entrypoint: /opt/keycloak/bin/kc.sh start
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak_postgres/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KC_METRICS_ENABLED: "true"
      KC_HEALTH_ENABLED: "true"
      KC_HTTP_ENABLED: "true"
      KC_PROXY: "edge"
      KC_HOSTNAME_STRICT: "false"
    labels:
      - "traefik.http.routers.keycloak.entrypoints=websecure"
      - "traefik.http.routers.keycloak.rule=Host(`keycloak.${APPDOMAIN:-local}`)"
      - "traefik.http.services.keycloak.loadbalancer.server.port=8080"
    networks:
      - traefik-network
    depends_on:
      - postgres
  postgres:
    image: postgres
    container_name: keycloak_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    volumes:
      - keycloak-storage:/var/lib/postgresql/data
    networks:
      - traefik-network



volumes:
  keycloak-storage:
  
networks:
    traefik-network:
      external: true
