version: '3'
services:
  mosqitto:
    image: eclipse-mosquitto
    container_name: mosqitto
    restart: always
    command: /usr/sbin/mosquitto -c /mosquitto-no-auth.conf
    ports:
      - 1883:1883
    volumes:
      - mosqitto-storage:/mosquitto/data
    networks:
      - traefik-network

volumes:
  mosqitto-storage:

networks:
    traefik-network:
      external: true
