version: '3'

services:
  portainer:
    image: mosqitto
    container_name: mosqitto
    restart: always
    ports:
      - 1883:1883
    volumes:
      - mosqitto-storage:/mosquitto/data
    networks:
      - traefik-network

volumes:
  mosqitto-storage:
