version: '3'
services:
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    restart: unless-stopped
    command: /usr/sbin/mosquitto -c /mosquitto-no-auth.conf
    ports:
      - 1883:1883
    volumes:
      - mosquitto-storage:/mosquitto/data
    networks:
      - traefik-network

volumes:
  mosquitto-storage:

networks:
    traefik-network:
      external: true
