version: '3'

services:
  traefik:
    image: traefik:v2.4
    container_name: traefik
    # Enables the web UI and tells Traefik to listen to docker
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.dnsmadeeasy.acme.dnschallenge=true"
      - "--certificatesresolvers.dnsmadeeasy.acme.dnschallenge.provider=dnsmadeeasy"
      - "--certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.dnsmadeeasy.acme.email=mikko@rauhala.net"
      - "--certificatesresolvers.dnsmadeeasy.acme.storage=/letsencrypt/acme.json"
    privileged: true
    labels:
      - "traefik.http.routers.traefik.rule=Host(`traefik.${APPDOMAIN:-local}`)"
      - "traefik.http.routers.traefik.tls.certresolver=dnsmadeeasy"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"
    ports:
      # HTTP port
      - "80:80"
      # HTTPS port
      - "443:443"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      - traefik-storage:/letsencrypt"
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - traefik-network

volumes:
  traefik-storage:
  
networks:
    traefik-network:
      external: true
