version: '3'

services:
  portainer:
    image: grafana/grafana
    container_name: grafana
    restart: always
    labels:
      - "traefik.http.routers.grafana.rule=Host(`grafana.${APPDOMAIN:-local}`)"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - traefik-network

volumes:
  grafana-storage:
  
networks:
    traefik-network:
      external: true
      
