version: '3'
services:
  nodered:
    image: nodered/node-red
    container_name: nodered
    restart: unless-stopped
    labels:
      - "traefik.http.routers.nodered.entrypoints=websecure"
      - "traefik.http.routers.nodered.rule=Host(`nodered.${APPDOMAIN:-local}`)"
      - "traefik.http.services.nodered.loadbalancer.server.port=1880"
    volumes:
      - nodered-storage:/data
    networks:
      - traefik-network

volumes:
  nodered-storage:

networks:
    traefik-network:
      external: true
