version: '3'

services:
  tftp:
    build: .
    image: tftp
    container_name: tftp
    restart: unless-stopped
    ports:
      - "69:69/udp"
    volumes:
      - /var/mnt/brick1/tftpboot:/tftpboot
