version: '3'
services:
  mongo:
    image: mongo:4.2
    container_name: mongo
    networks:
      - graylog-network
  # Elasticsearch: https://www.elastic.co/guide/en/elasticsearch/reference/7.10/docker.html
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2
    environment:
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    deploy:
      resources:
        limits:
          memory: 1g
    networks:
      - graylog-network
  # Graylog: https://hub.docker.com/r/graylog/graylog/
  graylog:
    image: graylog/graylog:4.0
    container_name: graylog
    environment:
      - GRAYLOG_HTTP_EXTERNAL_URI=https://graylog.${APPDOMAIN:-local}/
    entrypoint: /usr/bin/tini -- wait-for-it elasticsearch:9200 --  /docker-entrypoint.sh
    networks:
      - graylog-network
      - traefik-network
    restart: always
    depends_on:
      - mongo
      - elasticsearch
    ports:
      # Syslog TCP
      - 1514:1514
      # Syslog UDP
      - 1514:1514/udp
      # GELF TCP
      - 12201:12201
      # GELF UDP
      - 12201:12201/udp
    labels:
      - "traefik.http.routers.graylog.rule=Host(`graylog.${APPDOMAIN:-local}`)"
      - "traefik.http.services.graylog.loadbalancer.server.port=9000"
      - "traefik.http.routers.graylog.tls.certresolver=dnsmadeeasy"


networks:
  traefik-network:
    external: true
  graylog-network:
    driver: bridge
