version: '3'

services:
  geoweb:
    image: opengeoweb/geoweb
    container_name: geoweb
    restart: unless-stopped
    environment:
      - GW_APP_URL="https://geoweb.${APPDOMAIN:-local}"
      - GW_FEATURE_APP_TITLE="Meteo.FI GeoWeb"
      - GW_INITIAL_PRESETS_FILENAME="initialPresets.json"
      - GW_SCREEN_PRESETS_FILENAME="screenPresets.json"
      - GW_AUTH_CLIENT_ID="264496341656-41rbnl8ehtmt4r3426916bhmnullkhd9.apps.googleusercontent.com"
      - GW_AUTH_LOGIN_URL="https://accounts.google.com/o/oauth2/v2/auth?client_id={client_id}&response_type=code&scope=email+openid&redirect_uri={app_url}/code&state={state}"
      - GW_AUTH_TOKEN_URL="https://oauth2.googleapis.com/token"
      - GW_AUTH_LOGOUT_URL="{app_url}"
      - GW_INFRA_BASE_URL="https://api.opengeoweb.com"
    labels:
      - "traefik.http.routers.geoweb.entrypoints=websecure"
      - "traefik.http.routers.geoweb.rule=Host(`geoweb.${APPDOMAIN:-local}`)"
      - "traefik.http.services.geoweb.loadbalancer.server.port=8080"
    networks:
      - traefik-network
      
networks:
    traefik-network:
      external: true
