version: '3'

services:
  geoweb:
    image: opengeoweb/geoweb
    container_name: geoweb
    restart: unless-stopped
    environment:
      - GW_FEATURE_APP_TITLE="Meteo.FI GeoWeb"
    labels:
      - "traefik.http.routers.geoweb.entrypoints=websecure"
      - "traefik.http.routers.geoweb.rule=Host(`geoweb.${APPDOMAIN:-local}`)"
      - "traefik.http.services.geoweb.loadbalancer.server.port=8080"
    networks:
      - traefik-network
      
networks:
    traefik-network:
      external: true
