version: '3'

services:
  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    privileged: true
    restart: always
    labels:
      - "traefik.http.routers.portainer.rule=Host(`portainer.${APPDOMAIN:-local}`)"
      - "traefik.http.routers.portainer.tls.certresolver=dnsmadeeasy"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"
    volumes:
          # So that Portaomer can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-storage:/data
    networks:
      - traefik-network

volumes:
  portainer-storage:

networks:
    traefik-network:
      external: true
