version: '3'

services:
  influxdb:
    image: influxdb
    container_name: influxdb
    restart: always
    labels:
      - "traefik.http.routers.grafana.rule=Host(`influxdb.${APPDOMAIN:-local}`)"
      - "traefik.http.routers.grafana.tls.certresolver=dnsmadeeasy"
      - "traefik.http.services.grafana.loadbalancer.server.port=8086"
    volumes:
      - influxdb-volume:/var/lib/influxdb
    networks:
      - traefik-network

volumes:
  influxdb-storage:
  
networks:
    traefik-network:
      external: true
