version: '3'
services:
  influxdb:
    image: influxdb
    container_name: influxdb
    restart: always
    labels:
      - "traefik.http.routers.influxdb.entrypoints=websecure"
      - "traefik.http.routers.influxdb.rule=Host(`influxdb.${APPDOMAIN:-local}`)"
      - "traefik.http.services.influxdb.loadbalancer.server.port=8086"
    volumes:
      - influxdb-storage:/var/lib/influxdb
    networks:
      - traefik-network
  chronograf:
    image: chronograf
    container_name: chronograf
    restart: always
    command:
      - "--influxdb-url=http://influxdb:8086"
    labels:
      - "traefik.http.routers.chronograf.entrypoints=websecure"
      - "traefik.http.routers.chronograf.rule=Host(`chronograf.${APPDOMAIN:-local}`)"
      - "traefik.http.services.chronograf.loadbalancer.server.port=8888"
    volumes:
      - chronograf-storage:/var/lib/chronograf
    networks:
      - traefik-network

volumes:
  influxdb-storage:
  chronograf-storage:
  
networks:
    traefik-network:
      external: true
