version: '3'

services:
  influxdb:
    image: influxdb
    container_name: influxdb
    restart: always
    labels:
      - "traefik.http.routers.grafana.rule=Host(`influxdb.${APPDOMAIN:-local}`)"
      - "traefik.http.routers.grafana.tls.certresolver=dnsmadeeasy"
      - "traefik.http.services.grafana.loadbalancer.server.port=8086"
    volumes:
      - influxdb-storage:/var/lib/influxdb
    networks:
      - traefik-network
  chronograf:
    image: chronograf
    container_name: chronograf
    restart: always
    labels:
      - "traefik.http.routers.grafana.rule=Host(`influxdb.${APPDOMAIN:-local}`)"
      - "traefik.http.routers.grafana.tls.certresolver=dnsmadeeasy"
      - "traefik.http.services.grafana.loadbalancer.server.port=8888"
    volumes:
      - chronograf-storage:/var/lib/chronograf
    networks:
      - traefik-network

volumes:
  chronograf-storage:
  
networks:
    traefik-network:
      external: true
